### ISSUE TITLE
Zero-shot inference performance of CLIP in the paper

### ISSUE THREAD

**Issue by SanghyeokSon** [azshue/TPT#11]
Hi!

Given the Flowers102 dataset, 
Running the code without test time tuning yields results lower than the paper's zero-shot clip performance:

Result (60.94) < CLIP RN-50 (61.75)

How do you get the zero-shot inference performance in your experiments?

Sincerely,

**Comment by azshue** [comment]
Hi,

I used the default prompt for CLIP's zero-shot inference, which is "a photo of a". 
The performance difference you mentioned seems very small. You might want to check something like data split and data preprocessing. I hope this helps. Thanks!

Best,
