### ISSUE TITLE
Question about the test-time prompt learning procedure

### ISSUE THREAD

**Issue by 1215481871** [azshue/TPT#14]
Thanks for your work!

I am wondering that given a single test image and conduct the test-time prompt learning procedure, is this test image immediately evaluated on the optimized prompt?

Furthuremore, once the evaluation of a single test image is finished and the corresponding prompts is optimized, for the next coming test image, the prompts will be re-initialized to "a photo of a" or just using the optimized one from the previous step?

**Comment by azshue** [comment]
Hi, thank you for your interest in our work. To answer your questions:
1. Yes, the test image is evaluated immediately on the optimized prompt.
2. When a new test image comes in, the prompt will be reset to its initial state ("a photo of a" or the initial CoOp weight).

**Comment by 1215481871** [comment]
Thanks for your response! My confusion is resolved.

**Comment by Even-ok** [comment]
> Hi, thank you for your interest in our work. To answer your questions:
> 
> 1. Yes, the test image is evaluated immediately on the optimized prompt.
> 2. When a new test image comes in, the prompt will be reset to its initial state ("a photo of a" or the initial CoOp weight).
---
Hi, Thank you for your response! But I’m still curious about the reasoning behind resetting the prompts to their initial state when a new test image is introduced. Could you explain why the previous optimized prompt is not utilized for the next test image?

**Comment by azshue** [comment]
Hi @Even-ok ,

Sorry about the late response. Please check my comment under [this issue](https://github.com/azshue/TPT/issues/16#issuecomment-2406635448). I hope it answers your question. Let me know if you have other questions. Thanks!
