### ISSUE TITLE
Reproducing papers results - CoOp and CoCoop weights

### ISSUE THREAD

**Issue by taesiri** [azshue/TPT#3]
Hello,

Thank you for your excellent work and paper.

I want to reproduce the paper's results related to both ResNet and ViT-B/16 models. (Table 1 in the paper). Could you please highlight which weight files you used for CoOp and CoCoOp ?

**Comment by azshue** [comment]
Hello, 

Thank you for your interest in our work!

For CoOp, we use the [pre-trained weights](https://drive.google.com/file/d/18ypxfd82RR0pizc5MM1ZWDYDk4j0BtPF/view) released by its authors. The official pre-trained CoCoOp is not publicly available, so we trained our own CoCoOp model using the hyper-parameter setting provided in the original paper. However, we do not plan to release our reproduced CoCoOp. You could contact the author of CoCoOp or train a model yourself using its [official implementation](https://github.com/KaiyangZhou/CoOp/blob/main/COCOOP.md). 

Best,
Manli
