### ISSUE TITLE
Prompt Visualization

### ISSUE THREAD

**Issue by Zenvi** [azshue/TPT#6]
Hi, thank you for your work and code sharing.
I want to visualize the prompts after inputing an image, any ideas how?

**Comment by azshue** [comment]
Hi, 

Thank you for your interest in our work.
The learnable prompt is located in `PromptLearner`. After tuning it on an image, you could retrieve the learned prompt by inspecting `PromptLearner.ctx`. 
Our code doesn't provide any visualization tool for visualizing the prompt, but you could analyze the learned prompt with other open-source tools, for example, [this script](https://github.com/KaiyangZhou/CoOp/blob/main/interpret_prompt.py) provided in the CoOp codebase.

**Comment by Zenvi** [comment]
Thanks a lot for your reply! Closing the issue
