### ISSUE TITLE
What is the meaning of "Test-Time training"?

### ISSUE THREAD

**Issue by jingzhengli** [azshue/TPT#8]
Hi, recently I have trained a model **by using very small amount of unlabeled test data** (16-shot). Could I call this training manner "Test-Time training"? Thanks

**Comment by jingzhengli** [comment]
I have another question. During test-test training, why train the model by augmenting **only one sample** to multiple samples (**one origin** test sample in a batch), is it possible to **augment multiple test samples at once** (**many origin** test sample in a batch)?

**Comment by azshue** [comment]
> Hi, recently I have trained a model **by using very small amount of unlabeled test data** (16-shot). Could I call this training manner "Test-Time training"? Thanks

Hi, I think it depends on how you update your model at test time, and whether your model has been trained on some training data before test time. Please refer to [Sun et al.](https://arxiv.org/abs/1909.13231) for more details about their definition of "test-time training".

**Comment by azshue** [comment]
> I have another question. During test-test training, why train the model by augmenting **only one sample** to multiple samples (**one origin** test sample in a batch), is it possible to **augment multiple test samples at once** (**many origin** test sample in a batch)?

Yes, you can adapt our method to do batch test-time prompt tuning. However, in our paper, we consider a more practical and challenging setting, where at deployment (_i.e._, test-time), a model may not always have access to a batch of test samples, so we manage to do test-time adaptation on a single test sample.

**Comment by jingzhengli** [comment]
> > Hi, recently I have trained a model **by using very small amount of unlabeled test data** (16-shot). Could I call this training manner "Test-Time training"? Thanks
> 
> Hi, I think it depends on how you update your model at test time, and whether your model has been trained on some training data before test time. Please refer to [Sun et al.](https://arxiv.org/abs/1909.13231) for more details about their definition of "test-time training".

Thanks for you insightful response. My confusion is resolved.
